config/routes.rb
Rails.application.routes.draw do
  
  mount ActionCable.server => '/cable'
  devise_for :users
  
resources :blogs do
resources :comments, only: %i[create reply]

end 
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: "home#index"

get "category" ,to: "blogs#categories_blog_list" ,as: :categories_list

#list of user blogs with edit option
get "my_blogs" ,to: "blogs#my_blogs", as: :my_blogs

#delete blog 
get "delete_blog" ,to: "blogs#destroy", as: :delete_blog


#like the blogs in blogger 
  
get "like" ,to: "likes#like" , as: :like

get "unlike" ,to: "likes#unlike" , as: :unlike 

#comments reply 

  get "reply" ,to: "comments#reply" ,as: :reply 

  post "comment_reply",to: "comments#replies" ,as: :reply_comment

  get "delete_comment" ,to: "comments#delete" ,as: :delete_comment

  get "reply_delete" ,to: "comments#reply_delete", as: :reply_delete

  get "update",to: "comments#update",as: :update

  get "update_comment",to: "comments#update_comment", as: :update_comment

#profile route 

  get "/user/profile" ,to: "profile#profile" ,as: :user_profile

  get "/user/blog" , to: "profile#userblog" ,as: :user_blog
end

app/models/blog.rb
class Blog < ApplicationRecord

	acts_as_taggable_on :tags
  	acts_as_taggable_on :blog


	has_many :comments, dependent: :destroy
	has_many :likes , dependent: :destroy
	has_many :user_blog_visits ,class_name:"UserVisitBlog", dependent: :destroy
	has_many :comment_replies, dependent: :destroy
	belongs_to :master_categories ,class_name:"MasterCategory"
	belongs_to :user
	has_rich_text :description
	has_one_attached :description

	
	validates :title, :description ,:master_categories_id, presence: true
	validates :title ,uniqueness: true
	validates :title , length: { minimum: 10 }

	validates_presence_of :title , :message => 'Please Enter title.'
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: %i[ show edit update destroy ]
  before_action :set_category, only: %i[ new edit create ]



  # GET /blogs or /blogs.json
  def index
    @blogs = Blog.all.limit(3)  
  end

  def my_blogs
    if current_user != nil
    @blogs = Blog.paginate(page: params[:page],per_page: 4).where(user_id: current_user.id).order(created_at: :desc)
   
    end
  end 




  # GET /blogs/1 or /blogs/1.json
  def show
    if current_user != nil
    @likes = Like.find_by(user_id: current_user.id, blog_id: params[:id])
    @user = current_user.id
      end

      blog_visits(@blog.id)

    #fetch latest in index page 
    @latest = Blog.order(id: :desc).limit(3)

    #fetch recent viewed 
    if current_user != nil
    @viewed = UserVisitBlog.where(user_id: current_user.id).order(created_at: :desc).limit(3)
    end 
    

    @comment_replies = @blog.comment_replies.pluck(:comment_id)
    @allcomments = @blog.comments
    @comments = @allcomments.where.not(id: @comment_replies).order(created_at: :desc)
    
  end

  #categories list

  def categories_blog_list
    #fetch categories list from database
    @categories = MasterCategory.all

    #fetch blog based on categories 
    @cat_blog = Blog.paginate(page: params[:page],per_page: 6).where(master_categories_id: params[:cat_id]).order(created_at: :desc)
  end


 
  # GET /blogs/new
  def new
    @blog = Blog.new

  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs or /blogs.json
  def create
    @user = current_user
    @blog = @user.blogs.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to blog_url(@blog) }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1 or /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to blog_url(@blog), notice: "Blog was successfully updated." }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1 or /blogs/1.json
  def destroy
    @blog.destroy

    respond_to do |format|
      format.html { redirect_to root_path, notice: "Blog was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  def blog_visits(blog_id)  
      if current_user == nil  
          count_visit(blog_id)
      else
          @validate_visit = UserVisitBlog.find_by(blog_id: blog_id , user_id: current_user.id)

          if @validate_visit == nil
          @user_blog_visit = UserVisitBlog.new(blog_id: blog_id , user_id: current_user.id)
          @user_blog_visit.save!
          end 
      end 


  end

  #This function use for count the blog visit.
  def count_visit(blog_id)
          @visit_count = Blog.find(blog_id)
          count = @visit_count.visit_count
          @visit_count.visit_count =  count+=1  
          @visit_count.save!
  end


    def set_category
       @categories = MasterCategory.all

    end
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def blog_params
      params.require(:blog).permit(:title , :description,:master_categories_id,:tag_list)
    end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/_blog.html.erb
<div id="<%= dom_id blog %>">
  <% if action_name != "show" %>
    

    <%= link_to "Show this blog", blog, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this blog', edit_blog_path(blog), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  
  <% end %>
</div>

app/views/blogs/_form.html.erb
<%= form_with(model: blog, class: "contents") do |form| %>
  <% if blog.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3" id="notification" >
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
        <% blog.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<div class="py-2">
  <label for="title" class="block mb-2 text-lg font-medium text-[#4b4870] dark:text-gray-400">Title</label>
  <%= form.text_field :title ,:required => true ,class:"bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" %>
</div>
<div class="py-2">
  <label for="master_categories_id" class="block mb-2 text-lg font-medium text-[#4b4870] dark:text-gray-400">Select Category</label>
 <%= form.select :master_categories_id, @categories.map { |t| [t.name, t.id]}, {}, class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" ,:required => true %>
</div>
<div class="py-2">
<!--<%= form.select :tag_list, @categories.map { |t| [t.name, t.id]}, { :multiple => true }, class: "select bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" ,:required => true %>
-->
  <label for="tag_list" class="block mb-2 text-lg font-medium text-[#4b4870] dark:text-gray-400">Tags</label>
  <select class="select bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" multiple="multiple" id="blog_tag_list" >
  </select>
<input type="hidden" name="blog[tag_list]" id="tag_list" />
</div>

<div class="py-2">
  <label for="description" class="block mb-2 text-lg font-medium text-[#4b4870] dark:text-gray-400">Description</label>
  <%= form.rich_text_area :description ,:required => true ,class:"overflow-auto block p-2.5 w-full h-80 text-sm text-gray-900 bg-gray-50 rounded-lg border border-gray-300 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"%>
</div>
  <div class="py-2">
    <%= form.submit class: "blog_submit text-white bg-gradient-to-r from-cyan-500 to-blue-500 hover:bg-gradient-to-bl focus:ring-4 focus:outline-none focus:ring-cyan-300 dark:focus:ring-cyan-800 font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-2 mb-2 cursor-pointer" %>
      <%if params[:controller] == "blogs" && params[:action] == "edit" %>
    <div class="float-right py-2.5">
      <a id="delete_btn" class="cursor-pointer font-medium text-lg text-[#f0555f]">Delete this blog</a>
    </div>
    <%end%>
  
  </div>
<% end %>
   <!--modal for confirmation to delete blog-->

<div id="delete_blog_confirmation" tabindex="-1" class="hidden overflow-y-auto overflow-x-hidden fixed top-0 right-0 left-0 z-50 md:inset-0 h-modal md:h-full">
    <div class="relative p-4 w-full max-w-md h-full md:h-auto">
        <div class="relative bg-white rounded-lg shadow dark:bg-gray-700">
            <button type="button" id="close_delete_modal" class="absolute top-3 right-2.5 text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm p-1.5 ml-auto inline-flex items-center dark:hover:bg-gray-800 dark:hover:text-white" data-modal-toggle="popup-modal">
                <svg aria-hidden="true" class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>
                <span class="sr-only">Close modal</span>
            </button>
            <div class="p-6 text-center">
                <svg aria-hidden="true" class="mx-auto mb-4 w-14 h-14 text-gray-400 dark:text-gray-200" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 8v4m0 4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"></path></svg>
                <h3 class="mb-5 text-lg font-normal text-gray-500 dark:text-gray-400">Are you sure you want to delete this blog?</h3>
                 <%=link_to "Yes, I'm sure",delete_blog_path(id: params[:id]),class:"text-white bg-red-600 hover:bg-red-800 focus:ring-4 focus:outline-none focus:ring-red-300 dark:focus:ring-red-800 font-medium rounded-lg text-sm inline-flex items-center px-5 py-2.5 text-center mr-2"%>                
                <button type="button"  id="cancel_delete" class="text-gray-500 bg-white hover:bg-gray-100 focus:ring-4 focus:outline-none focus:ring-gray-200 rounded-lg border border-gray-200 text-sm font-medium px-5 py-2.5 hover:text-gray-900 focus:z-10 dark:bg-gray-700 dark:text-gray-300 dark:border-gray-500 dark:hover:text-white dark:hover:bg-gray-600 dark:focus:ring-gray-600">No, cancel</button>
            </div>
        </div>
    </div>
</div>

<!--javascript-->
<script>
/* select2 tags system */
$('.select').select2({
    tags: true,
    tokenSeparators: [',', ' ']
});

/* modal for confirmation to delete*/
$(document).ready(function(){
    $("#delete_btn").click(function(){
      $("#delete_blog_confirmation").show();
    });

   $("#close_delete_modal").click(function(){
      $("#delete_blog_confirmation").hide();
    });

    $("#cancel_delete").click(function(){
        $("#delete_blog_confirmation").hide();
      });
  });


/* this function is used to convert array into string for thag input field */
function set_tag_string(){
var set_string = $('#blog_tag_list').val().join(',');
$("#tag_list").val(set_string);
}

/* this function is used for the on click blog submit button that time it set the value of tags by calling the function */
$(document).ready(function() {
    $('.blog_submit').click(function() {
        set_tag_string();
    });
});
</script>

app/views/blogs/edit.html.erb
<%=render "home/navigation"%>

<div class="flex flex-row flex-wrap justify-center content-center bg-[#f9f9fe] py-10">
  <div class="w-8/12 bg-white px-20 py-10">
  <div class="text-center mb-4">
    <span class="text-2xl font-semibold text-[#4b4870]">Edit Blog</span>
  </div>
  <%= render "form", blog: @blog %>
  </div>
</div>

<%= render "home/footer"%>


 

app/views/blogs/new.html.erb
<%= render "home/navigation"%>
<div class="flex flex-row flex-wrap justify-center content-center bg-[#f9f9fe] py-10">
  <div class="w-8/12 bg-white px-20 py-10">
  <div class="text-center mb-4">
    <span class="text-2xl font-semibold text-[#4b4870]">Create Blog</span>
  </div>
  <%= render "form", blog: @blog %>
  </div>
</div>

<%=render "home/footer"%>

app/views/blogs/show.html.erb
<%= render "home/navigation" %>
<div class="p-5 bg-[#f9f9fe]" ></div>
<section class="bg-[#f9f9fe]">
    <div class="flex flex-row flex-wrap justify-start content-start item-start px-10">
        <div class="w-3/4 px-16">
            <div class="mb-10 shadow-md bg-white hover:shadow-lg dark:border-gray-700 dark:bg-gray-800 dark:hover:bg-gray-700 relative rounded-lg">
               
                <div class="flex flex-col flex-wrap justify-center content-center item-center">
                    <!-- image section --> 
                    <div class="">
                        <img src="<%= @blog&.rich_text_description&.embeds&.first&.url %>" />
                    </div>
                    <!--title-->
                    <div class="flex flex-col justify-center content-center item-center px-16 pb-6">
                            
                            <div class="pt-10 pb-6 text-center">
                                <span class="text-4xl font-semibold text-[#4b4870]"><%= @blog.title %></span>
                            </div>

                            <div class="flex flex-row flex-wrap justify-center content-center item-center">
                            <div class="pr-3 flex flex-col flex-wrap content-center justify-center">
                                <div>
                                  <span class="text-md font-semibold text-[#4b4870]"><%= @blog.created_at.strftime("%d %b %Y")%></span>
                                </div>
                            </div>
                            <div class="px-3 flex flex-row flex-wrap justify-left content-center">
                            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6 inline stroke-2 stroke-[#f0555f]">
                                <path stroke-linecap="round" stroke-linejoin="round" d="M12 20.25c4.97 0 9-3.694 9-8.25s-4.03-8.25-9-8.25S3 7.444 3 12c0 2.104.859 4.023 2.273 5.48.432.447.74 1.04.586 1.641a4.483 4.483 0 01-.923 1.785A5.969 5.969 0 006 21c1.282 0 2.47-.402 3.445-1.087.81.22    1.668.337 2.555.337z" />
                            <span class="float text-[#5e6676] ml-2 text-xl leading-4 font-semibold text-[#4b4870]"><sub><%= @blog.comments.count%></sub></span>
                            </svg>
                        
                            </div>
                            <div class="px-2 flex flex-row flex-wrap justify-left content-center">
                                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6 inline stroke-2 stroke-[#f0555f] ">
                                    <path stroke-linecap="round" stroke-linejoin="round" d="M6.633 10.5c.806 0 1.533-.446 2.031-1.08a9.041 9.041 0 012.861-2.4c.723-.384 1.35-.956 1.653-1.715a4.498 4.498 0 00.322-1.672V3a.75.75 0 01.75-.75A2.25 2.25 0 0116.5 4.5c0 1.152-.26 2.243-.723 3.218-.266.558.107 1.282.725 1.282h3.126c1.026 0 1.945.694 2.054 1.715.045.422.068.85.068 1.285a11.95 11.95 0 01-2.649 7.521c-.388.482-.987.729-1.605.729H13.48c-.483 0-.964-.078-1.423-.23l-3.114-1.04a4.501 4.501 0 00-1.423-.23H5.904M14.25 9h2.25M5.904 18.75c.083.205.173.405.27.602.197.4-.078.898-.523.898h-.908c-.889 0-1.713-.518-1.972-1.368a12 12 0 01-.521-3.507c0-1.553.295-3.036.831-4.398C3.387 10.203 4.167 9.75 5 9.75h1.053c.472 0 .745.556.5.96a8.958 8.958 0 00-1.302 4.665c0 1.194.232 2.333.654 3.375z" />
                                    <span class="text-[#5e6676] ml-2 text-xl leading-4 text-xl font-semibold text-[#4b4870]"><sub><%= @blog.likes.count %></sub></span>
                                </svg>
                            </div>
                            <div class="px-2 flex flex-row flex-wrap justify-left content-center">
                                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6 inline stroke-2 stroke-[#f0555f]">
                                    <path stroke-linecap="round" stroke-linejoin="round" d="M2.036 12.322a1.012 1.012 0 010-.639C3.423 7.51 7.36 4.5 12 4.5c4.638 0 8.573 3.007 9.963 7.178.07.207.07.431 0 .639C20.577 16.49 16.64 19.5 12 19.5c-4.638 0-8.573-3.007-9.963-7.178z" />
                                    <path stroke-linecap="round" stroke-linejoin="round" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
                                     <span class="text-[#5e6676] ml-2 text-xl leading-4 font-semibold text-[#4b4870]"><sub><%=@blog.visit_count %></sub></span>
                                </svg>
                            </div>
                        </div>
            </div>  
                    <!--description-->
                    <div class="px-16 pb-10 ">
                        <span class="text-base text-[#5e6676] text-lg font-medium antialiased"><%= @blog.description.to_s %></span>
                    </div> 
                    <div class="px-16 pb-10 ">
                         <div class="flex flex-row flex-wrap justify-center content-center item-center">
                        <% @blog.tags.each do |g| %>
                            <div class=" bg-white py-1 px-5 mr-4 mb-2 rounded-full border border-[#f0555f] border-l-4 border-solid border-y-zinc-200 border-r-zinc-200">
                                <span class="text-[#4b4870]"><%= g.name.capitalize %></span>   
                            </div>
                        <% end %>
                    </div>
                    </div>
                    <%if current_user != nil%>
                    <div class="px-16 pb-10">
                         <div class="flex flex-row flex-wrap justify-center content-center item-center">
                            <div class="py-2 px-5 mr-2">
                            <% if @likes == nil%>
                                <%= render partial:  "likes/like" , locals: {like: Like.new} %>
                            <% else%>
                            <%= turbo_stream_from "unlike" %>
                            <%= render partial:  "likes/unlike" , locals: {unlike: Like.new} %>
                            <%end%>
                            </div>
                        </div>
                    </div>
                    <%end%>

            </div>  
         </div>
          <div class="p-10 mb-10 shadow-md bg-white hover:shadow-lg dark:border-gray-700 dark:bg-gray-800 dark:hover:bg-gray-700 relative rounded-lg">
                <div class="flex flex-col flex-wrap justify-center content-center item-center">
                      
                    <div class="flex flex-row justify-center ">
                         <%if @blog.user.image.attached?%>
                        <div class="object-cover">
                        <%=image_tag @blog.user.image.variant(resize: "150x150") ,class:"rounded-lg"%>
                       </div>
                        <%else%>
                        <div>
                        <%=image_tag "user_default.png",class:"rounded-full h-24 w-24"%>
                        </div>
                        <%end%>
                    </div>
                    <div class="text-center p-3">
                        <span class="text-2xl text-[#5e6676]"><%=@blog.user.name.capitalize%></span>
                    </div>  
                    <div class="px-10 text-center leading-7">
                    <%if @blog.user.about != nil%>
                        <span class=" text-[#5e6676] text-base font-medium antialiased text-center"><%=@blog.user.about.capitalize%></span>
                    <%else%>
                        <span class=" text-[#5e6676] text-base font-medium antialiased text-center"></span>
                    <%end%>
                    </div>
                    <div class="flex flex-row justify-center content-center item-center pt-6">
                        <div class="mr-3">
                            <svg class="h-6 w-6 text-[#4267B2] cursor-pointer"  viewBox="0 0 24 24"  fill="none"  stroke="currentColor"  stroke-width="2"  stroke-linecap="round"  stroke-linejoin="round">  <path d="M18 2h-3a5 5 0 0 0-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 0 1 1-1h3z" /></svg>
                        </div>
                        <div class="mr-3">
                            <svg class="h-6 w-6 text-red-600 cursor-pointer"  viewBox="0 0 24 24"  fill="none"  stroke="currentColor"  stroke-width="2"  stroke-linecap="round"  stroke-linejoin="round">  <rect x="2" y="2" width="20" height="20" rx="5" ry="5" />  <path d="M16 11.37A4 4 0 1 1 12.63 8 4 4 0 0 1 16 11.37z" />  <line x1="17.5" y1="6.5" x2="17.51" y2="6.5" /></svg>
                        </div>
                        <div class="mr-3">
                            <svg class="h-6 w-6 text-[#1DA1F2] cursor-pointer"  viewBox="0 0 24 24"  fill="none"  stroke="currentColor"  stroke-width="2"  stroke-linecap="round"  stroke-linejoin="round">  <path d="M23 3a10.9 10.9 0 0 1-3.14 1.53 4.48 4.48 0 0 0-7.86 3v1A10.66 10.66 0 0 1 3 4s-4 9 5 13a11.64 11.64 0 0 1-7 2c9 5 20 0 20-11.5a4.5 4.5 0 0 0-.08-.83A7.72 7.72 0 0 0 23 3z" /></svg>
                        </div>
                </div>
                             
            </div>  
         </div>
            <div class="p-10 mb-10 shadow-md bg-white hover:shadow-lg dark:border-gray-700 dark:bg-gray-800 dark:hover:bg-gray-700 relative rounded-lg">
                <div class="flex flex-col flex-wrap justify-center content-center item-center">
                    <div class="text-center">
                        <span class="text-4xl font-semibold text-[#4b4870]">Comments</span>
                    </div>
                    <div class="pt-5 w-full">
                        <%if current_user != nil%>
                        <div class="">
                         <%= render partial: "comments/form", locals: { comment: Comment.new } %>
                        </div>
                         <%end%>
                         <%= turbo_stream_from @blog, :comments %>
                         <div id="<%= "#{dom_id(@blog)}_comments" %>">             
                        </div>
                       


                <!--master commnent section-->
                    <%@comments.each do |comment|%>
                        <div class="p-10 w-full flex flex-col justify-start content-start item-start border-b-2 border-solid border-gray">
                            <div class="flex flex-row flex-wrap justify-start content-start">
                            <%if comment.user.image.attached?%>
                        <div class="object-cover h-14 w-14">
                        <%=image_tag comment.user.image.variant(resize: "100x100") ,class:"w-14 h-14 rounded-full"%>
                       </div>
                        <%else%>
                        <div>
                        <%=image_tag "user_default.png",class:"rounded-full h-14 w-14"%>
                        </div>
                        <%end%>
                            <div class="flex flex-col justify-start content-center px-6">
                            <div>
                                <span class="text-xl text-[#5e6676]"><%= comment.user.name.capitalize %></span>
                                <%if current_user != nil%>
                                    <%if current_user.id == comment.user.id%>
                                        <span class="px-2"><%=link_to "Delete" ,delete_comment_path(comment_id: comment.id,blog_id: comment.blog_id),class:"text-[#f0555f] text-sm"%></span>
                                    <%end%>
                                <%end%>
                            </div>
                            <div>
                                <span class="text-xs font-semibold text-[#D3D3D3] "><%= distance_of_time_in_words(comment.created_at, 76.seconds.from_now) %></span>
                            </div>
      
                            </div>
                        </div>
                        <div class="px-20 py-4">
                            <span class="text-[#5e6676] text-base font-medium antialiased "><%= comment.body %></span>
                        </div>
                        <div class="py-5 px-20">
                            <span class="text-[#4b4870]"><%=link_to "Reply" ,reply_path(comment_id: comment.id ,blog_id: comment.blog_id),class:""%> - <%= comment.reply.count%> </span>
                        <%if current_user != nil%>
                            <%if current_user.id == comment.user.id%>
                            <span class="text-[#d3d3d3]"> | <%=link_to "Edit",update_path(comment_id: comment.id,blog_id: comment.blog_id)%></span>
                            <%end%>
                        <%end%>   
                        </div>
                       
                    

                    </div>
                <%end%>

                    </div>               
                </div>  
            </div>
        </div>

    <!-- quicklinks -->
        <%= render "home/quicklinks" %> 
    </div>
</section>
<%= render "home/footer" %>
<script>

/* like */
  $(document).ready(function(){
    $(".like").click(function(){
      $(".like").hide();
      $(".unlike").show();
    });
  });
/* unlike to like */
  $(document).ready(function(){
    $(".unlike").click(function(){
      $(".unlike").hide();
      $(".like").show();
    });
  });

</script>