config/routes.rb
Rails.application.routes.draw do
  
  mount ActionCable.server => '/cable'
  devise_for :users
  
resources :blogs do
resources :comments, only: %i[create reply]

end 
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: "home#index"

get "category" ,to: "blogs#categories_blog_list" ,as: :categories_list

#list of user blogs with edit option
get "my_blogs" ,to: "blogs#my_blogs", as: :my_blogs

#delete blog 
get "delete_blog" ,to: "blogs#destroy", as: :delete_blog


#like the blogs in blogger 
  
get "like" ,to: "likes#like" , as: :like

get "unlike" ,to: "likes#unlike" , as: :unlike 

#comments reply 

  get "reply" ,to: "comments#reply" ,as: :reply 

  post "comment_reply",to: "comments#replies" ,as: :reply_comment

  get "delete_comment" ,to: "comments#delete" ,as: :delete_comment

  get "reply_delete" ,to: "comments#reply_delete", as: :reply_delete

  get "update",to: "comments#update",as: :update

  get "update_comment",to: "comments#update_comment", as: :update_comment

#profile route 

  get "/user/profile" ,to: "profile#profile" ,as: :user_profile

  get "/user/blog" , to: "profile#userblog" ,as: :user_blog
end

app/models/comment.rb
class Comment < ApplicationRecord

	include ActionView::RecordIdentifier

	belongs_to :user
	belongs_to :blog
	#has_many :comment_replies, class_name:"CommentReply" , dependent: :delete_all
	has_many :comment ,class_name: 'CommentReply',foreign_key: "comment_id", dependent: :destroy
	has_many :reply ,class_name: 'CommentReply' ,foreign_key: "reply_id" , dependent: :destroy

		
  	after_create_commit { broadcast_prepend_to [blog, :comments], target: "#{dom_id(blog)}_comments" }

  	validates_presence_of :body

   	#after_create_commit { broadcast_prepend_to [@comment,:comments], target: "#{dom_id(comment)}_comments" }


end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :comment, only: %i[ reply ]

	  def create
    @blog = Blog.find(params[:blog_id])
    @comment = @blog.comments.new(comment_params)  
    @master_comment_id = params[:comment][:comment_id].to_i

  if @master_comment_id != 0
      respond_to do |format|
      if @comment.save 
        comment_reply(@master_comment_id, @comment.id)
        format.turbo_stream { render turbo_stream: turbo_stream.replace('comment_form', partial: 'comments/form', locals: { comment: Comment.new })}
        format.html { render partial: 'comments/form', locals: { comment: Comment.new }}
      else
        format.turbo_stream { render turbo_stream: turbo_stream.replace('comment_form', partial: 'comments/form', locals: { comment: @comment }) }
        format.html { render partial: 'comments/form', locals: { comment: @comment }}
      end
    end
  else
      respond_to do |format|
      if @comment.save 
        format.turbo_stream { render turbo_stream: turbo_stream.replace('comment_form', partial: 'comments/form', locals: { comment: Comment.new })}
        format.html { render partial: 'comments/form', locals: { comment: Comment.new }}
      else
        format.turbo_stream { render turbo_stream: turbo_stream.replace('comment_form', partial: 'comments/form', locals: { comment: @comment }) }
        format.html { render partial: 'comments/form', locals: { comment: @comment }}
      end
    end
  end 

  end 


  #this section for when we use single form for the
        #if @reply_id != nil
        # comment_reply(@reply_id, @comment.id)

        #end

  def reply
       @blog = Blog.find(params[:blog_id])
       @comment = CommentReply.where(reply_id: params[:comment_id]).order(created_at: :desc)

       @master_comment = Comment.find(params[:comment_id])
  end


  def delete
      delete = Comment.find(params[:comment_id])
     if delete.destroy           
        redirect_to blog_path(params[:blog_id])
     end 
  end 


  def reply_delete
    delete = Comment.find(params[:reply_id])
    if delete.destroy
      redirect_to reply_path(comment_id: params[:comment_id],blog_id: params[:blog_id])
    end 
  end


  def update
    @categories = MasterCategory.all
		#fetch latest in index page 
		@latest = Blog.order(id: :desc).limit(3)
    		#fetch recent viewed 
		if current_user != nil
      @viewed = UserVisitBlog.where(user_id: current_user.id).order(created_at: :desc).limit(3)
      end 
      @comment = Comment.find(params[:comment_id])
  end


  def update_comment
    update = Comment.find(params[:comment_id])
    master_comment_id = params[:master_comment_id]
    if update.update(body: params[:body])
        if master_comment_id.empty?
          redirect_to blog_path(params[:blog_id]) 
        else
          redirect_to reply_path(comment_id: params[:master_comment_id],blog_id: params[:blog_id]) 
        end
    end
  end


  

  private 

  

  def comment_reply(master_comment_id,reply_comment_id)
    @blog = Blog.find(params[:blog_id]) 
      @reply = @blog.comment_replies.new
      @reply.comment_id = reply_comment_id
      @reply.reply_id = master_comment_id
      @reply.save!
  end


  def comment
   # @comment = Comment.find(params[:comment_id])
    #fetch latest 
    @latest = Blog.order(id: :desc).limit(3)

    #fetch recent viewed 
    if current_user != nil
    @viewed = UserVisitBlog.where(user_id: current_user.id).order(created_at: :desc).limit(3)
    end
  end


  def comment_params
    params.require(:comment).permit(:body,:user_id)
  end


end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div class=" p-10 w-full mt-5 flex flex-col justify-start content-start item-start" id="<%= dom_id(comment) %>">
  
  <div class="flex flex-row flex-wrap justify-start content-start">
    <div>
    <img src="http://127.0.0.1:3000/assets/user_default-649704301cb9c912fb0472b01f54871a4ce38869c9941c41432a5b7414dfc148.png" class="rounded-full w-14 h-14"/>
      </div>
    <div class="flex flex-col justify-start content-center px-5">
      <div>
        <span class="text-2xl text-[#5e6676]"><%= comment.user.name.capitalize %></span>
        <span class="px-2"><%=link_to "Delete",reply_delete_path(blog_id: params[:blog_id] , comment_id: params[:comment_id]) ,class:"text-[#f0555f] text-sm"%></span>                       
      </div>
      <div>
        <span class="text-xs font-semibold text-[#4b4870] "><%= distance_of_time_in_words(comment.created_at, 76.seconds.from_now)     %></span>
      </div>
      
    </div>
  </div>
<div class="px-20 py-4">
  <span class="text-[#5e6676] text-base font-medium antialiased "><%= comment.body %></span>
</div>

  <div class="px-20 py-4">
  <span class="text-[#d3d3d3]"><%=link_to "Edit",reply_path(comment_id: comment.id ,blog_id: comment.blog_id),class:""%></span>
  </div>
 
</div>

app/views/comments/_comment_btn.html.erb
<div class="py-5">

        <%=link_to "Reply" ,reply_path(comment_id: comment.id ,blog_id: comment.blog_id),class:"text-green-700 hover:text-white border border-green-700 hover:bg-green-800 focus:ring-4 focus:outline-none focus:ring-green-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-2 mb-2 dark:border-green-500 dark:text-green-500 dark:hover:text-white dark:hover:bg-green-600 dark:focus:ring-green-800"%> 
</div>
<div class="py-5">

        <%=link_to "Reply" ,reply_path(comment_id: comment.id ,blog_id: comment.blog_id),class:"text-green-700 hover:text-white border border-green-700 hover:bg-green-800 focus:ring-4 focus:outline-none focus:ring-green-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-2 mb-2 dark:border-green-500 dark:text-green-500 dark:hover:text-white dark:hover:bg-green-600 dark:focus:ring-green-800"%> 
 
<%if current_user.id = comment.user.id %>
<div class="py-5">

        <%=link_to "Reply" ,reply_path(comment_id: comment.id ,blog_id: comment.blog_id),class:"text-green-700 hover:text-white border border-green-700 hover:bg-green-800 focus:ring-4 focus:outline-none focus:ring-green-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-2 mb-2 dark:border-green-500 dark:text-green-500 dark:hover:text-white dark:hover:bg-green-600 dark:focus:ring-green-800"%> 
</div>
<%end%>

app/views/comments/_form.html.erb
<% if current_user != nil %>
<%= turbo_frame_tag "comment_form" do %>
  <%= form_with model: comment, url: blog_comments_path(@blog) do |form| %>
    
    <% if params[:comment_id] != nil %>
          <% @comment_id = params[:comment_id] %> 
    <% end %>
 
    <% if comment.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

        <ul>
          <% comment.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <%= form.text_field :body ,class:"block p-4 w-full h-36 text-gray-900 bg-gray-50 rounded-lg border border-gray-300 sm:text-md focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"%>
    <%= form.hidden_field :user_id , value: current_user.id %> 
    <%= form.hidden_field :comment_id , value: @comment_id %> 
    <%= form.submit "Comment", class:"text-white bg-green-700 hover:bg-green-800 focus:outline-none focus:ring-4 focus:ring-green-300 font-medium rounded-full text-sm px-5 py-2.5 text-center mr-2 mb-2 mt-3 dark:bg-green-600 dark:hover:bg-green-700 dark:focus:ring-green-800"%>
  <% end %>
<% end %>
<%end %>

app/views/comments/reply.html.erb
<%= render "home/navigation" %>
 
<section class="bg-[#f9f9fe] pt-10">
    <div class="flex flex-row flex-wrap justify-start content-start item-start px-10">
        <div class="w-3/4 px-16">
            <div class=" bg-white mb-10 p-10 shadow-md hover:shadow-lg dark:border-gray-700 dark:bg-gray-800 dark:hover:bg-gray-700 relative rounded-lg">
                <div class="flex flex-col flex-wrap justify-center content-center item-center">
                    <div class="pt-5 w-full">
                        <div class="text-center">
                            <span class="text-4xl font-semibold text-[#4b4870]">Comment Replies</span>
                        </div>
                        <div class="">
                        <div class="py-10 px-5 w-full flex flex-col justify-start content-start item-start">
                            <div class="flex flex-row flex-wrap justify-start content-start">
                            <%if @master_comment.user.image.attached?%>
                        <div class="object-cover h-14 w-14">
                        <%=image_tag @master_comment.user.image.variant(resize: "100x100") ,class:"w-14 h-14 rounded-full"%>
                       </div>
                        <%else%>
                        <div>
                        <%=image_tag "user_default.png",class:"rounded-full h-14 w-14"%>
                        </div>
                        <%end%>
                            <div class="flex flex-col justify-start content-center px-6">
                                <div>
                                    <span class="text-xl text-[#5e6676]"><%= @master_comment.user.name.capitalize %></span>
                                </div>
                                <div>
                                    <span class="text-xs font-semibold text-[#D3D3D3] "><%= distance_of_time_in_words(@master_comment.created_at, 76.seconds.from_now) %></span>
                                </div>
                            </div>
                        </div>
                        <div class="px-20 py-3">
                            <span class="text-[#5e6676] text-base font-medium antialiased "><%= @master_comment.body %></span>
                        </div>
                    </div>
                        </div>
                            <%if current_user != nil%>
                         <div class="px-5 mb-5">
                         <%= render partial: "comments/form", locals: { comment: Comment.new } %>
                        </div>
                            <%= turbo_stream_from @blog, :comments %>
                                <div id="<%= "#{dom_id(@blog)}_comments" %>">
                                </div>
                            <%end%>

                            <!--nested comment section-->
                        <%@comment.each do |comment|%>
                        <div class="py-5 px-5 w-full flex flex-col justify-start content-start item-start">
                            <div class="flex flex-row flex-wrap justify-start content-start ">
                            <%if comment.comment.user.image.attached?%>
                        <div class="object-cover h-14 w-14">
                        <%=image_tag comment.comment.user.image.variant(resize: "100x100") ,class:"w-14 h-14 rounded-full"%>
                       </div>
                        <%else%>
                        <div>
                        <%=image_tag "user_default.png",class:"rounded-full h-14 w-14"%>
                        </div>
                        <%end%>
                            <div class="flex flex-col justify-start content-center px-6">
                            <div>
                                <span class="text-xl text-[#5e6676]"><%= comment.comment.user.name.capitalize %></span>
                                <%if current_user != nil%>
                                <%if current_user.id == comment.comment.user.id%>
                                <span class="px-2"><%=link_to "Delete",reply_delete_path(reply_id: comment.comment.id,blog_id: params[:blog_id],comment_id: params[:comment_id]) ,class:"text-[#f0555f] text-sm"%></span>
                                <%end%>
                                <%end%>
                            </div>
                            <div>
                                <span class="text-xs font-semibold text-[#D3D3D3] "><%= distance_of_time_in_words(comment.comment.created_at, 76.seconds.from_now) %></span>
                            </div>
      
                            </div>
                        </div>
                        <div class="px-20 py-4">
                            <span class="text-[#5e6676] text-base font-medium antialiased "><%= comment.comment.body %></span>
                        </div>
                        <%if current_user != nil%>
                        <%if current_user.id == comment.comment.user.id%>
                        <div class="pt-2 pb-10 px-20 border-b-2 border-solid border-gray">
                              <%if current_user.id == comment.comment.user.id%>
                            <span class="text-[#d3d3d3]"><%=link_to "Edit",update_path(comment_id: comment.comment.id,blog_id: params[:blog_id], master_id: params[:comment_id]),class:""%></span>
                            <%end%>
                        </div>
                        <%end%>
                        <%end%>
                    </div>
                <%end%>

                    </div>  
                </div>  
            </div>
          
        </div>

    <!-- quicklinks -->
        <%= render "home/quicklinks" %> 
    </div>
</section>
<%= render "home/footer" %>

app/views/comments/update.html.erb
<%= render "home/navigation" %>
 
<section class="bg-[#f9f9fe] pt-10">
    <div class="flex flex-row flex-wrap justify-start content-start item-start px-10">
        <div class="w-3/4 px-16">
            <div class="mb-10 p-10 shadow-md bg-white hover:shadow-lg dark:border-gray-700 dark:bg-gray-800 dark:hover:bg-gray-700 relative rounded-lg">
                <div class="flex flex-col flex-wrap justify-center content-center item-center">
                    <div class="pt-5 w-full">
                        
                        <div class="text-center">
                            <span class="text-4xl font-semibold text-[#4b4870]">Comment Update</span>
                        </div>
                        <div class="pt-10 px-20">
                       <%= form_with url: update_comment_path,method: :get do |form| %>
                        <%= form.text_field :body , value: @comment.body,class:"block p-4 w-full h-36 text-gray-900 bg-gray-50 rounded-lg border border-gray-300 sm:text-md focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"%>
                        <%=form.hidden_field :comment_id , value: params[:comment_id]%>
                        <%=form.hidden_field :blog_id , value: params[:blog_id]%>
                        <%=form.hidden_field :master_comment_id , value: params[:master_id]%>
                        <%= form.submit "update", class:"text-white bg-green-700 hover:bg-green-800 focus:outline-none focus:ring-4 focus:ring-green-300 font-medium rounded-full text-sm px-5 py-2.5 text-center mr-2 mb-2 mt-3 dark:bg-green-600 dark:hover:bg-green-700 dark:focus:ring-green-800"%>
                        <% end %>
                        </div>
                    </div>  
                </div>  
            </div>
          
        </div>

    <!-- quicklinks -->
        <%= render "home/quicklinks" %> 
    </div>
</section>
<%= render "home/footer" %>