config/routes.rb
Rails.application.routes.draw do
  
  mount ActionCable.server => '/cable'
  devise_for :users
  
resources :blogs do
resources :comments, only: %i[create reply]

end 
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: "home#index"

get "category" ,to: "blogs#categories_blog_list" ,as: :categories_list

#list of user blogs with edit option
get "my_blogs" ,to: "blogs#my_blogs", as: :my_blogs

#delete blog 
get "delete_blog" ,to: "blogs#destroy", as: :delete_blog


#like the blogs in blogger 
  
get "like" ,to: "likes#like" , as: :like

get "unlike" ,to: "likes#unlike" , as: :unlike 

#comments reply 

  get "reply" ,to: "comments#reply" ,as: :reply 

  post "comment_reply",to: "comments#replies" ,as: :reply_comment

  get "delete_comment" ,to: "comments#delete" ,as: :delete_comment

  get "reply_delete" ,to: "comments#reply_delete", as: :reply_delete

  get "update",to: "comments#update",as: :update

  get "update_comment",to: "comments#update_comment", as: :update_comment

#profile route 

  get "/user/profile" ,to: "profile#profile" ,as: :user_profile

  get "/user/blog" , to: "profile#userblog" ,as: :user_blog
end

app/models/like.rb
class Like < ApplicationRecord

	belongs_to :user
	belongs_to :blog

	  after_create_commit { broadcast_append_to('unlike') }
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

	def like
    @likes = Like.new(user_id: current_user.id , blog_id: params[:blog_id])
    respond_to do |format|
      if @likes.save!
      		format.turbo_stream{render turbo_stream: turbo_stream.prepend('unlike', partial: 'likes/unlike')}
      else
       	
      end
    end
	end 

	def unlike 

		@unlike = Like.find_by(user_id: current_user.id , blog_id: params[:blog_id])
		respond_to do |format|
      if @unlike.destroy
        format.turbo_stream { render turbo_stream: turbo_stream.replace('like_button', partial: 'likes/like', locals: { like: Like.new }) }
        format.html { render partial: 'likes/like', locals: { like: Like.new }}
      else
        format.turbo_stream { render turbo_stream: turbo_stream.replace('unlike_button', partial: 'likes/unlike', locals: { like: @like }) }
        format.html { render partial: 'likes/unlike', locals: { like: @like }}
      end
    end

	end


end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/likes/_like.html.erb
<%= turbo_frame_tag dom_id(like) do %>
    <%=link_to "Like Blog" , like_path(blog_id: @blog.id),class:"like focus:outline-none text-white bg-[#4b4870] hover:bg-purple-800 focus:ring-4 focus:ring-[#4b4870] font-medium rounded-lg text-sm px-5 py-2.5 mb-2 dark:bg-[#4b4870] dark:hover:bg-purple-700 dark:focus:ring-[#4b4870]" %> 
     <%=link_to "Unlike" , unlike_path(blog_id: @blog.id),class:"unlike focus:outline-none text-white bg-[#4b4870] hover:bg-purple-800 focus:ring-4 focus:ring-[#4b4870] font-medium rounded-lg text-sm px-5 py-2.5 mb-2 dark:bg-[#4b4870] dark:hover:bg-purple-700 dark:focus:ring-[#4b4870] hidden"%> 
<% end %>

app/views/likes/_unlike.html.erb
<%= turbo_frame_tag dom_id(unlike) do %>
    <%=link_to "Unlike" , unlike_path(blog_id: @blog.id),class:" unlike focus:outline-none text-white bg-[#4b4870] hover:bg-purple-800 focus:ring-4 focus:ring-[#4b4870] font-medium rounded-lg text-sm px-5 py-2.5 mb-2 dark:bg-[#4b4870] dark:hover:bg-purple-700 dark:focus:ring-[#4b4870]" %> 
     <%=link_to "Like Blog" , like_path(blog_id: @blog.id),class:"like focus:outline-none text-white bg-[#4b4870] hover:bg-purple-800 focus:ring-4 focus:ring-[#4b4870] font-medium rounded-lg text-sm px-5 py-2.5 mb-2 dark:bg-[#4b4870] dark:hover:bg-purple-700 dark:focus:ring-[#4b4870] hidden" %> 
<% end %>