config/routes.rb
Rails.application.routes.draw do
  
  mount ActionCable.server => '/cable'
  devise_for :users
  
resources :blogs do
resources :comments, only: %i[create reply]

end 
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: "home#index"

get "category" ,to: "blogs#categories_blog_list" ,as: :categories_list

#list of user blogs with edit option
get "my_blogs" ,to: "blogs#my_blogs", as: :my_blogs

#delete blog 
get "delete_blog" ,to: "blogs#destroy", as: :delete_blog


#like the blogs in blogger 
  
get "like" ,to: "likes#like" , as: :like

get "unlike" ,to: "likes#unlike" , as: :unlike 

#comments reply 

  get "reply" ,to: "comments#reply" ,as: :reply 

  post "comment_reply",to: "comments#replies" ,as: :reply_comment

  get "delete_comment" ,to: "comments#delete" ,as: :delete_comment

  get "reply_delete" ,to: "comments#reply_delete", as: :reply_delete

  get "update",to: "comments#update",as: :update

  get "update_comment",to: "comments#update_comment", as: :update_comment

#profile route 

  get "/user/profile" ,to: "profile#profile" ,as: :user_profile

  get "/user/blog" , to: "profile#userblog" ,as: :user_blog
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	 before_action :fetch_list, only: %i[index]
	
	def index
		#fetch all blog in index page
		@blogs = Blog.paginate(page: params[:page],per_page: 5).order(created_at: :desc)
	end

	private

	def fetch_list
		
		#fetch categories list from database
		@categories = MasterCategory.all

		#fetch latest in index page 
		@latest = Blog.order(id: :desc).limit(3)

		#fetch recent viewed 
		if current_user != nil
		@viewed = UserVisitBlog.where(user_id: current_user.id).order(created_at: :desc).limit(3)
		end 
	end
	 
	
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_Bloglist.html.erb
<section class="bg-[#f9f9fe] px-24">
    <div class="flex flex-row flex-wrap justify-between content-start item-start">
        <div class="w-8/12">
            <% @blogs.each do | b | %>
                <!-- This is the Tiles section of blogger  -->
            <div class="mb-10 shadow-md bg-white hover:shadow-lg dark:border-gray-700 dark:bg-gray-800 dark:hover:bg-gray-700 rounded">
                <div class="float-right p-1">
                <!--edit blog icon-->
                
                <%if current_user != nil %>
                    <%if b.user_id ==  current_user.id%>
                        <a href="/blogs/<%=b.id%>/edit">
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-8 h-8 stroke-[#f0555f]">
                            <path stroke-linecap="round" stroke-linejoin="round" d="M16.862 4.487l1.687-1.688a1.875 1.875 0 112.652 2.652L10.582 16.07a4.5 4.5 0 01-1.897 1.13L6 18l.8-2.685a4.5 4.5 0 011.13-1.897l8.932-8.931zm0 0L19.5 7.125M18 14v4.75A2.25 2.25 0 0115.75 21H5.25A2.25 2.25 0 013 18.75V8.25A2.25 2.25 0 015.25 6H10" />
                        </svg>
                        </a>
                    <%end%>
                <%end%>
                </div>
                <div class="px-16 py-14">
                <div class="flex flex-row flex-wrap justify-center content-center item-center">
                   <% if b&.rich_text_description&.embeds&.first&.url != nil%>
                    <div class="w-1/4">
                        <img src="<%= b&.rich_text_description&.embeds&.first&.url %>" class="w-40 h-30 rounded">
                    </div>  
                    <div class=" w-3/4  flex flex-col flex-wrap justify-start align-start conten-start">
                        <% else %>
                    <div class=" w-full flex flex-col flex-wrap justify-start align-start conten-start">
                    <%end%>
                        <div class="w-full">
                        <% if b.title.size > 25 %>  
                         <p class="text-3xl font-semibold text-[#4b4870]"><%=h truncate(b.title.capitalize, :length => 60) %></p>
                        <% else %>
                        <p class="text-4xl font-semibold text-[#4b4870] py-2 mb-3"><%= b.title.capitalize%></p>      
                        <% end %>
                        </div>
                        <div class="flex flex-row flex-wrap justify-start content-center item-center mt-3">
                            <div class="pr-3 flex flex-col flex-wrap content-center justify-center">
                                <div>
                                  <span class="text-md font-semibold text-[#4b4870]"><%= b.created_at.strftime("%d %b %Y")%></span>
                                </div>
                            </div>
                            <div class="px-3 flex flex-row flex-wrap justify-left content-center">
                            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6 inline stroke-2 stroke-[#f0555f]">
                                <path stroke-linecap="round" stroke-linejoin="round" d="M12 20.25c4.97 0 9-3.694 9-8.25s-4.03-8.25-9-8.25S3 7.444 3 12c0 2.104.859 4.023 2.273 5.48.432.447.74 1.04.586 1.641a4.483 4.483 0 01-.923 1.785A5.969 5.969 0 006 21c1.282 0 2.47-.402 3.445-1.087.81.22    1.668.337 2.555.337z" />
                            <span class="float text-[#5e6676] ml-2 text-xl leading-4 font-semibold text-[#4b4870]"><sub><%= b.comments.count%></sub></span>
                            </svg>
                        
                            </div>
                            <div class="px-2 flex flex-row flex-wrap justify-left content-center">
                                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6 inline stroke-2 stroke-[#f0555f] ">
                                    <path stroke-linecap="round" stroke-linejoin="round" d="M6.633 10.5c.806 0 1.533-.446 2.031-1.08a9.041 9.041 0 012.861-2.4c.723-.384 1.35-.956 1.653-1.715a4.498 4.498 0 00.322-1.672V3a.75.75 0 01.75-.75A2.25 2.25 0 0116.5 4.5c0 1.152-.26 2.243-.723 3.218-.266.558.107 1.282.725 1.282h3.126c1.026 0 1.945.694 2.054 1.715.045.422.068.85.068 1.285a11.95 11.95 0 01-2.649 7.521c-.388.482-.987.729-1.605.729H13.48c-.483 0-.964-.078-1.423-.23l-3.114-1.04a4.501 4.501 0 00-1.423-.23H5.904M14.25 9h2.25M5.904 18.75c.083.205.173.405.27.602.197.4-.078.898-.523.898h-.908c-.889 0-1.713-.518-1.972-1.368a12 12 0 01-.521-3.507c0-1.553.295-3.036.831-4.398C3.387 10.203 4.167 9.75 5 9.75h1.053c.472 0 .745.556.5.96a8.958 8.958 0 00-1.302 4.665c0 1.194.232 2.333.654 3.375z" />
                                    <span class="text-[#5e6676] ml-2 text-xl leading-4 text-xl font-semibold text-[#4b4870]"><sub><%= b.likes.count %></sub></span>
                                </svg>
                            </div>
                            <div class="px-2 flex flex-row flex-wrap justify-left content-center">
                                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6 inline stroke-2 stroke-[#f0555f]">
                                    <path stroke-linecap="round" stroke-linejoin="round" d="M2.036 12.322a1.012 1.012 0 010-.639C3.423 7.51 7.36 4.5 12 4.5c4.638 0 8.573 3.007 9.963 7.178.07.207.07.431 0 .639C20.577 16.49 16.64 19.5 12 19.5c-4.638 0-8.573-3.007-9.963-7.178z" />
                                    <path stroke-linecap="round" stroke-linejoin="round" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
                                     <span class="text-[#5e6676] ml-2 text-xl leading-4 font-semibold text-[#4b4870]"><sub><%=b.visit_count %></sub></span>
                                </svg>
                            </div>
                        </div>
                    </div> 
                </div>                  
                <div class="pt-4 pb-2">  
                <span class="leading-7 text-[#5e6676] text-base font-medium "><%= truncate(b.description.to_plain_text, :length => 280) %></span> 
                </div>
                <!--This is tag and user profile display section-->
                <div class=" flex flex-row flex-wrap justify-start content-center item-center">
                     <div class=" w-8/12  flex flex-row flex-wrap justify-start content-center ">
                        <% b.tags.limit(3).each do |tags| %>
                            <div class=" bg-white py-1 px-5 mr-4 rounded-full border border-[#f0555f] border-l-4 border-solid border-y-zinc-200 border-r-zinc-200">
                                <span class="text-[#4b4870]"><%= tags.name.capitalize %></span>   
                            </div>
                        <% end %>
                    </div>  
                    <div class="w-4/12 flex flex-row justify-end content-center py-2">
                        <div class="flex items-center space-x-4">
                             <%if b.user.image.attached?%>
                        <div class="object-cover h-10 w-10">
                        <%=image_tag b.user.image.variant(resize: "100x100") ,class:"w-10 h-10 rounded-full"%>
                       </div>
                        <%else%>
                        <div>
                        <%=image_tag "user_default.png",class:"rounded-full h-10 w-10"%>
                        </div>
                        <%end%>
                       <!--     <img class="w-10 h-10 rounded-full" src="https://ghost.estudiopatagon.com/maktub/content/images/size/w300h300/2022/05/mixkit-man-holding-the-brim-of-a-yellow-fedora-that-covers-93-desktop-wallpaper.png" alt="UserImage">
                           --> <div class="font-medium dark:text-white">
                                <div><%= b.user.name.capitalize%></div>
                                <div class="text-sm text-gray-500 dark:text-gray-400">Joined in <%= b.user.created_at.strftime("%b %Y")%></div>
                            </div>
                        </div>
                    </div>   
                </div>
                <div class="flex flex-row justify-center content-center mt-3">
                <%= link_to "Continue Reading",blog_path(b.id) ,class:"text-white bg-[#4b4870] dark:focus:ring-cyan-800 font-medium rounded-full text-sm px-6 py-3 text-center"%>
                </div>
            </div>
        </div>   
    <%end%>
        <div class="flex flex-row justify-center pb-14">
                <%= will_paginate @blogs %>                    
        </div>
    </div>
   
    <!-- quicklinks -->
        <%= render "quicklinks" %> 

    </div>
</section>

app/views/home/_callaction.html.erb
<section class="relative pt-36 lg:pb-10 overflow-hidden bg-black">
  <img class="absolute top-0 left-1/2 transform -translate-x-1/2" src="gradia-assets/elements/cta/radial.png" alt="">
  <div class="relative z-10 container mx-auto px-4 mb-12">
    <div class="flex flex-wrap -m-6">
      <div class="w-full lg:w-1/2 p-6">
        <div class="lg:max-w-xl">
          <h2 class="mb-6 font-heading font-bold text-6xl sm:text-7xl text-white">Get maximum results from all your projects.</h2>
          <p class="mb-20 text-base text-white">Amet minim mollit non deserunt ullamco est sit aliqua.</p>
          <button class="mb-11 font-heading font-semibold w-full lg:w-auto p-5 text-xs text-white bg-blue-600 hover:bg-blue-700 uppercase rounded-md tracking-px">Create blog</button>
        </div>
      </div>
    </div>
  </div>
  <div class="pl-4 lg:w-1/2 lg:absolute lg:bottom-0 lg:right-0">
    <img class="relative z-10 ml-auto transform hover:-translate-x-28 transition ease-in-out duration-500" src="gradia-assets/images/cta/screen.png" alt="">
  </div>
</section>

app/views/home/_categories.html.erb
<section class="bg-[#f9f9fe] px-24 py-8">
    <div class="flex flex-row flex-wrap justify-start content-center">
        <%@categories.each do | c |%>
            <%if params["cat_id"] == c.id.to_s %>
             <%=link_to c.name, categories_list_path(cat_id: c.id ),class:"rounded-full border-2 border-solid border-[#4b4870] px-5 py-1 mr-2 text-white bg-[#4b4870]" %>
            <%else%>
             <%=link_to c.name, categories_list_path(cat_id: c.id ),class:"rounded-full border-2 border-solid border-gray px-5 py-1 mr-2 text-gray-500  hover:bg-[#4b4870] hover:text-white hover:border-[#4b4870] hover:shadow-md " %>
            <%end%>
        <%end%>
    </div>
</section>

app/views/home/_footer.html.erb
<footer class="p-4 rounded-lg shadow md:px-6 md:py-8 dark:bg-gray-900">
    <div class="sm:flex sm:items-center sm:justify-between px-20">
        
            <span class="self-center  text-[#4b4870] text-2xl font-semibold whitespace-nowrap dark:text-white">Blogger</span>
        
        <ul class="flex flex-wrap items-center mb-6 text-sm text-gray-500 sm:mb-0 dark:text-gray-400">
         
            <li>
                <a href="#" class="mr-4 hover:underline md:mr-6 ">About</a>
            </li>
            <li>
                <a href="#" class="mr-4 hover:underline md:mr-6">Privacy Policy</a>
            </li>
            <li>
                <a href="#" class="mr-4 hover:underline md:mr-6 ">Licensing</a>
            </li>
            <li>
                <a href="#" class="hover:underline">Contact</a>
            </li>
        </ul>
    </div>
    <hr class="my-6 border-gray-200 sm:mx-auto dark:border-gray-700 lg:my-8">
    <span class="block text-sm text-gray-500 sm:text-center dark:text-gray-400">© 2022 <a href="https://flowbite.com/" class="hover:underline">Blogger</a>. All Rights Reserved.
    </span>
</footer>

app/views/home/_navigation.html.erb
<div class="relative bg-white">
  <div class="max-w-7xl mx-auto px-4 sm:px-6">
    <div class="flex justify-between items-center border-b-2 border-gray-100 py-6 md:justify-start md:space-x-10">
      <div class="flex justify-start lg:w-0 lg:flex-1 pl-10">
        <a href="#">
          <span class="sr-only">Workflow</span>
          <img class="h-8 w-auto sm:h-10" src="https://tailwindui.com/img/logos/workflow-mark.svg?color=indigo&shade=600" alt="">
        </a>
      </div>
      <div class="-mr-2 -my-2 md:hidden">
        <button type="button" class="bg-white rounded-md p-2 inline-flex items-center justify-center text-gray-400 hover:text-gray-500 hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-inset focus:ring-indigo-500" aria-expanded="false">
          <span class="sr-only">Open menu</span>
          <!-- Heroicon name: outline/menu -->
          <svg class="h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" d="M4 6h16M4 12h16M4 18h16" />
          </svg>
        </button>
      </div>
      <nav class="hidden md:flex space-x-10 w-96">
        
        <%if params[:controller] == "home" && params[:action] == "index"%>
        <%= link_to "Home" , root_path ,class:"text-base font-medium text-[#4b4870] hover:text-gray-900 border-solid border-[#4b4870] border-b-2"%>
        <%else%>
        <%= link_to "Home" , root_path ,class:"text-base font-medium text-[#4b4870] hover:text-gray-900"%>
        <%end%>
        
        
        <%if current_user != nil%>
        <%if params[:controller] == "blogs" && params[:action] == "my_blogs"%>
        <%= link_to "My Blogs" ,my_blogs_path,class:"ext-base font-medium text-[#4b4870] hover:text-gray-900 border-solid border-[#4b4870] border-b-2"%>
        <%else%>
        <%= link_to "My Blogs" ,my_blogs_path,class:"ext-base font-medium text-[#4b4870] hover:text-gray-900"%>
        <%end%>
        <%end%>
       
        <a href="#" class="text-base font-medium text-gray-500 hover:text-gray-900"> About </a>

        <a href="#" class="text-base font-medium text-[#4b4870] hover:text-gray-900"> Contact us</a>
        
      </nav>
      <div class="hidden md:flex items-center justify-end md:flex-1 lg:w-0 pr-10">

        <% if current_user == nil%>
        <%=link_to "Signin", new_user_session_path,class:"whitespace-nowrap text-base font-medium text-[#4b4870] hover:text-[#4b4870]" %>
          
        <%= link_to "Signup",new_user_registration_path,class:"ml-8 whitespace-nowrap inline-flex items-center justify-center px-4 py-2 border border-transparent rounded-md shadow-sm text-base font-medium text-white bg-[#4b4870] hover:bg-[#4b4872]" %>
        <%else%>
        <%if params["controller"] == "blogs" && params["action"] == "new"%>
        <%=link_to "My Blogs" , new_blog_path ,class:"ml-8 whitespace-nowrap inline-flex items-center justify-center px-4 py-2 border border-transparent rounded-md shadow-sm text-base font-medium text-white bg-[#4b4870] hover:bg-[#4b4870]" %>
        <%else%>
        <%=link_to "Create Blog" , new_blog_path ,class:"ml-8 whitespace-nowrap inline-flex items-center justify-center px-4 py-2 border border-transparent rounded-md shadow-sm text-base font-medium text-white bg-[#4b4870] hover:bg-[#4b4870]" %>
        <%end%>
     <!--<%= link_to "logout", destroy_user_session_path ,data: { turbo_method: "delete" },class:"whitespace-nowrap text-base font-medium text-gray-500 hover:text-gray-900" %>  -->
        
         <div class="ml-3 relative">
          <div>
            <button type="button" class="bg-gray-800 flex text-sm rounded-full focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-gray-800 focus:ring-white" id="user-menu-button" aria-expanded="false" aria-haspopup="true">
              <span class="sr-only">Open user menu</span>
              <%if current_user.image.attached?%>
                        <div class="object-cover h-10 w-10">
                        <%=image_tag current_user.image.variant(resize: "100x100") ,class:"w-10 h-10 rounded-full"%>
                       </div>
                  <%else%>
                        <div>
                        <%=image_tag "user_default.png",class:"rounded-full h-10 w-10"%>
                        </div>
               <%end%>
          <!--    <img class="h-10 w-10 rounded-full" src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80" alt="">
          -->  </button>
          </div>
          <div class="origin-top-right absolute right-0 mt-2 w-48 rounded-md shadow-lg py-1 bg-white ring-1 ring-black ring-opacity-5 focus:outline-none hidden" role="menu" aria-orientation="vertical" aria-labelledby="user-menu-button" tabindex="-1" id="user-menu-list">
            <!-- Active: "bg-gray-100", Not Active: "" -->
             <% if current_user != nil %>
            <%= link_to "Your Profile", user_profile_path ,class:"block px-4 py-2 text-sm text-gray-700"%>
            <%= link_to "Sign out", destroy_user_session_path ,data: { turbo_method: "delete" } ,class:"block px-4 py-2 text-sm text-gray-700"%>
            <%end%>
           </div>
        </div>

        <%end%>
      </div>
    </div>
  </div>

 <script>
 $(document).ready(function(){
    $("#user-menu-button").click(function(){
      $("#user-menu-list").slideToggle();
    });
  });
 </script>

app/views/home/_quicklinks.html.erb
        
    <div class="w-3/12 flex flex-col flex-wrap justify-start content-start">    
        <div class="mb-10">
            <span class="text-2xl font-semibold text-[#4b4870]">Latest Articles</span>   
            <% @latest.each do | l | %>
            <div class="flex flex-col flex-wrap justify-start content-start mt-6">
                <div class="flex flex-row flex-wrap justify-start">
                       
                        <div class="w-4/12">  
                         <% if l&.rich_text_description&.embeds&.first&.url != nil %>
                            <img src="<%= l&.rich_text_description&.embeds&.first&.url %>" class="rounded-md" >
                        <%else%>
                            <%= image_tag "#{l.master_categories.name.downcase}.jpeg", class:"rounded-md"%>
                        <%end%>
                        </div>

                        <div class="w-8/12 flex flex-col justify-start pl-2">
                            <%=link_to truncate(l.title.capitalize, :length => 20),blog_path(l.id),class:"text-lg font-semibold text-[#4b4870]"%>                        
                           <!--<span class="text-lg font-semibold text-[#4b4870]"><%=h truncate(l.title.capitalize, :length => 20) %></span> -->
                            <span class="text-xs font-semibold text-[#4b4870] mt-1"><%= l.created_at.strftime("%d %b %Y") %></span>
                        </div>
                </div>
            </div>
            <%end%>         
        </div>

        <!--recently viewed panel -->
        <% if user_signed_in? %>
        <div class="recent_viewed mb-10">
            <span class="text-2xl font-semibold text-[#4b4870]">Recently Viewed</span>   
            <% @viewed.each do | v |%>
            <div class="flex flex-col flex-wrap justify-start content-start mt-6">
                <div class="flex flex-row flex-wrap justify-start content-start">
                        <div class="w-4/12">  
                            <% if v&.blog&.rich_text_description&.embeds&.first&.url != nil %>
                            <img src="<%= v&.blog&.rich_text_description&.embeds&.first&.url %>" class="rounded-md" >
                        <%else%>
                            <%= image_tag "#{v.blog.master_categories.name.downcase}.jpeg", class:"rounded-md"%>
                        <%end%> </div>
                        <div class="w-8/12 flex flex-col justify-start pl-2">
                            <%=link_to truncate(v.blog.title.capitalize, :length => 20),blog_path(v.blog.id),class:"text-lg font-semibold text-[#4b4870]"%>
                           <!-- <span class="text-lg font-semibold text-[#4b4870]"><%=h truncate(v.blog.title.capitalize, :length => 20) %></span> -->
                            <span class="text-xs font-semibold text-[#4b4870] mt-1"><%= v.blog.created_at.strftime("%d %b %Y") %></span>
                        </div>
                </div>
            </div>
            <% end %>
        </div>
        <% end %>
        <!-- social links -->
        <div class="mb-10">
             <span class="text-2xl font-semibold text-[#4b4870]">Follow Me!</span>
                <div class="flex flex-row justify-start content-start item-start pt-6">
                    <div class="mr-3">
                    <svg class="h-10 w-10 text-[#4267B2] cursor-pointer"  viewBox="0 0 24 24"  fill="none"  stroke="currentColor"  stroke-width="2"  stroke-linecap="round"  stroke-linejoin="round">  <path d="M18 2h-3a5 5 0 0 0-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 0 1 1-1h3z" /></svg>
                </div>
                <div class="mr-3">
                <svg class="h-10 w-10 text-red-600 cursor-pointer"  viewBox="0 0 24 24"  fill="none"  stroke="currentColor"  stroke-width="2"  stroke-linecap="round"  stroke-linejoin="round">  <rect x="2" y="2" width="20" height="20" rx="5" ry="5" />  <path d="M16 11.37A4 4 0 1 1 12.63 8 4 4 0 0 1 16 11.37z" />  <line x1="17.5" y1="6.5" x2="17.51" y2="6.5" /></svg>
                </div>
                <div class="mr-3">
                <svg class="h-10 w-10 text-[#1DA1F2] cursor-pointer"  viewBox="0 0 24 24"  fill="none"  stroke="currentColor"  stroke-width="2"  stroke-linecap="round"  stroke-linejoin="round">  <path d="M23 3a10.9 10.9 0 0 1-3.14 1.53 4.48 4.48 0 0 0-7.86 3v1A10.66 10.66 0 0 1 3 4s-4 9 5 13a11.64 11.64 0 0 1-7 2c9 5 20 0 20-11.5a4.5 4.5 0 0 0-.08-.83A7.72 7.72 0 0 0 23 3z" /></svg>
                </div>
                </div>
                
        </div>

    </div>

app/views/home/_recent.html.erb
 <span class="text-2xl font-semibold text-[#4b4870]">Recently Viewed</span>   
            <% @viewed.each do | v |%>
            <div class="flex flex-col flex-wrap justify-start content-start pt-6">
                <div class="flex flex-row flex-wrap justify-start content-start">
                        <div class="w-3/12">  
                            <img src="https://ghost.estudiopatagon.com/maktub/content/images/size/w300h300/2022/05/mixkit-man-holding-the-brim-of-a-yellow-fedora-that-covers-93-desktop-wallpaper.png">
                        </div>
                        <div class="w-9/12 px-3 flex flex-col justify-start content-start">
                           <div class="">
                            <span class="text-ls font-semibold text-[#4b4870]"><%=v.blog.title, blog_path(v.id) %></span> 
                        </div>
                        <div class="">
                            <span class="text-xs font-semibold text-[#4b4870]"><%= v.blog.created_at.to_formatted_s(:short) %></span>
                        </div>
                        </div>
                </div>
            </div>
            <% end %>

app/views/home/index.html.erb
<!-- render naviagation bar --> 
<%= render "navigation" %>
<!--render call action -->
<!-- render categories -->
<%= render "categories" %>

<!-- render blog list -->
<%= render "Bloglist" %>

<%= render "footer" %>

 